### ISSUE TITLE
Incompability with Lethal things?

### ISSUE THREAD

**Issue by R3xxion** [LegaSource/AddonFusion#1]
[Error  : Unity Log] NullReferenceException
Stack trace:
AddonFusion.Patches.PlayerControllerBPatch.FixVehicleParent (GrabbableObject& _currentlyGrabbingObject) (at C:/Users/Geoffrey/source/repos/AddonFusion/AddonFusion/Patches/PlayerControllerBPatch.cs:21)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::BeginGrabObject>(GameNetcodeStuff.PlayerControllerB)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<GameNetcodeStuff.PlayerControllerB::BeginGrabObject>?-1609622098(GameNetcodeStuff.PlayerControllerB)
LethalThings.PouchyBelt.PlayerControllerB_BeginGrabObject (On.GameNetcodeStuff.PlayerControllerB+orig_BeginGrabObject orig, GameNetcodeStuff.PlayerControllerB self) (at O:/github/LethalThings/LethalThings/MonoBehaviours/PouchyBelt.cs:42)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<GameNetcodeStuff.PlayerControllerB::BeginGrabObject>?-476120324(GameNetcodeStuff.PlayerControllerB)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Interact_performed>(GameNetcodeStuff.PlayerControllerB,UnityEngine.InputSystem.InputAction/CallbackContext)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray1[System.Action1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_001B)
UnityEngine.InputSystem.LowLevel.<>cDisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

[Error  : Unity Log] NullReferenceException while executing 'performed' callbacks of 'Movement/Interact[/Keyboard/e]'

**Comment by R3xxion** [comment]
also note: It softlocks the game, even not be able to go to orbit or go back in

**Comment by LegaSource** [comment]
Yes I'm looking into something else but I have the fix for that (didn't reproduce after so I think it's good)

**Comment by LegaSource** [comment]
I've published a new version, I haven't reproduced the issue with this one, if you can try on your end!
