### ISSUE TITLE
[Suggestion] Bug spray

### ISSUE THREAD

**Issue by MathiusXII** [LegaSource/AddonFusion#3]
Could you add an addon for spray paint that causes hoarder bugs, snare fleas, and bunker spiders to run away from you and occasionally damages them when you spray it at them?

**Comment by LegaSource** [comment]
I've started working on a new addon, I only need to finish the code now
I want it to be able to drive away bees (both from the nest and the Butler's)
I might add a configuration to include other creatures that could be affected if you want
This wanted this new addon for the WeedKiller
