### ISSUE TITLE
Items stored in cruiser teleporting outside near ship.

### ISSUE THREAD

**Issue by Common-Say** [LegaSource/AddonFusion#4]
Putting items in the company cruiser sometimes causes them to teleport just outside of the ship, on the other side of where the cruiser would be stowed. This happens especially often when putting them on the floor of the vehicle, as apposed to on one of the shelves.

![20240803214344_1](https://github.com/user-attachments/assets/b6735b70-f3bb-46db-819d-d72289ed7810)

**Comment by LegaSource** [comment]
Hi, I wasn't able to reproduce the issue
If you have a method to do it, I'm interested

**Comment by Common-Say** [comment]
Just tested it and the recent update seems to have fixed it, loaded 12 radar boosters into the cruiser and none of the twelve teleported. Thank you!

**Comment by Common-Say** [comment]
I've taken another look at it, and it seems to be a conflict with LethalLib. I think it should be noted however, that I am using a more powerful computer than the one I first discovered the issue with, which was a Steam Deck and I don't remember requiring LethalLib to trigger the teleports. I am still using a linux-based system to run the game as well.

To reproduce the issue:
1. Install AddonFusion and LethalLib, as well as its dependency HookGenPatcher.
    * Optionally install an infinite money mod to make testing easier.
2. Buy the company cruiser and 12 radar boosters. Other items may work and I did first notice it with scrap, but I used radar boosters for testing.
3. Place the radar boosters onto the shelves or floor of the vehicle until you notice one disappears, or one is floating near the ship.

Note that it may take a few seconds for the item to teleport.

I was able to reproduce it with, in total, BepinEx, TerminalApi, TerminalMoney, LCBetterSaves, HookGenPatcher, LethalLib, and AddonFusion installed. All of the mods were up-to-date, with AddonFusion being 1.0.5. I am fairly certain BepinEx, TerminalApi, TerminalMoney, LCBetterSaves, and HookGenPatcher are not involved in the bug.

**Comment by LegaSource** [comment]
Thanks for the infos
LethalLib was required for AddonFusion to work, but I forgot to list it as a dependency, I'll check if I can reproduce the issue with your instructions

**Comment by TechTonic02** [comment]
Is there any update on this?

**Comment by LegaSource** [comment]
I'm sorry, but I haven't had the time to work on that mod again yet
I've been quite busy with other mods and my personal life
However, it hasn't been abandoned, I will get back to it soon, and I have several other ideas to implement
Sorry for the delay, and thanks for your patience

**Comment by TechTonic02** [comment]
Its all good, looking forward to when it updates

**Comment by LegaSource** [comment]
Hello, I released an update about a week ago, have you encountered the issue since then?

**Comment by TechTonic02** [comment]
I haven’t check in for awhile, but yes me and my friends haven’t experienced this issue since the update

**Comment by LegaSource** [comment]
Alright, thanks for the feedback
